/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            requestId: string;
                            method: string;
                            url: string;
                            statusCode: number;
                            durationMs: number;
                            /** Format: date-time */
                            startedAt: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            repo: string;
                            sessions: number;
                            turns: number;
                            inputTokens: number;
                            outputTokens: number;
                            costUsd: number | null;
                            lastSeenAt: string | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description YYYY-MM-DD, Asia/Seoul */
                            day: string;
                            sessions: number;
                            turns: number;
                            outputTokens: number;
                            costUsd: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            nudged: number;
                            complied: number;
                            rate: number | null;
                            bypassed: number;
                            /** Format: date-time */
                            bypassedBefore: string;
                            events: {
                                id: number;
                                sessionId: string;
                                repo: string | null;
                                /** Format: date-time */
                                ts: string;
                                triggerSkill: string;
                                outcome: "nudged" | "throttled";
                                complied: boolean;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/skills/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    weeks?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            weeks: string[];
                            rows: {
                                skill: string;
                                /** @description weeks와 같은 길이, 같은 순서 */
                                counts: number[];
                                total: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    repo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: string;
                            repo: string;
                            gitBranch: string | null;
                            /** Format: date-time */
                            startedAt: string;
                            /** Format: date-time */
                            lastSeenAt: string;
                            turns: number;
                            models: string[];
                            outputTokens: number;
                            costUsd: number | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            session: {
                                id: string;
                                cwd: string;
                                repo: string;
                                gitBranch: string | null;
                                cliVersion: string | null;
                                /** Format: date-time */
                                startedAt: string;
                                /** Format: date-time */
                                lastSeenAt: string;
                            };
                            turns: {
                                id: string;
                                /** Format: date-time */
                                ts: string;
                                model: string;
                                inputTokens: number;
                                cacheReadTokens: number;
                                cacheCreationTokens: number;
                                outputTokens: number;
                                costUsd: number | null;
                            }[];
                            skills: {
                                id: string;
                                /** Format: date-time */
                                ts: string;
                                skill: string;
                                source: "tool" | "command";
                            }[];
                            totalCostUsd: number | null;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            thresholds: {
                                minEvents: number;
                                deadMultiplier: number;
                                quietMultiplier: number;
                                deadFloorDays: number;
                            };
                            rules: {
                                /** @description 스킬 이름, 또는 "gate:<trigger>" */
                                name: string;
                                kind: "skill" | "gate";
                                status: "dead" | "quiet" | "ok" | "insufficient";
                                total: number;
                                /** Format: date-time */
                                firstAt: string;
                                /** Format: date-time */
                                lastAt: string;
                                silenceDays: number;
                                medianGapDays: number | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/harness/brain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            dir: string;
                            docs: {
                                /** @description frontmatter가 있는 문서 수 */
                                total: number;
                                active: number;
                                draft: number;
                                superseded: number;
                                /** @description status 값이 셋 중 어느 것도 아닌 문서 */
                                other: number;
                            };
                            staleDays: number;
                            /** @description active 인데 updated 가 60일 넘은 문서, 오래된 순 */
                            stale: {
                                id: string;
                                path: string;
                                kind: string;
                                /** @description frontmatter의 updated, YYYY-MM-DD */
                                updated: string;
                                ageDays: number;
                            }[];
                            inbox: {
                                items: number;
                                /** @description 날짜 접두어가 없어 나이를 모르는 항목 */
                                undated: number;
                                oldestAgeDays: number | null;
                            };
                            cadence: {
                                weeks: {
                                    /** @description ISO 주, 예 2026-W36 */
                                    week: string;
                                    commits: number;
                                }[];
                                julyBaselinePerWeek: number;
                                last4WeeksPerWeek: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description 기록된 결정 전체 */
                            total: number;
                            /** @description 추천이 있고 답도 읽힌 결정. 동의율의 분모 */
                            judged: number;
                            agreed: number;
                            rate: number | null;
                            items: {
                                id: number;
                                sessionId: string;
                                repo: string | null;
                                /** Format: date-time */
                                ts: string;
                                header: string;
                                question: string;
                                options: string[];
                                recommended: string | null;
                                chosen: string | null;
                                agreed: boolean | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            current: {
                                id: number;
                                trigger: "startup" | "interval" | "manual";
                                status: "running" | "done" | "failed";
                                /** Format: date-time */
                                startedAt: string;
                                finishedAt: string | null;
                                files: number | null;
                                turns: number | null;
                                skills: number | null;
                                gates: number | null;
                                decisions: number | null;
                                error: string | null;
                            } | null;
                            recent: {
                                id: number;
                                trigger: "startup" | "interval" | "manual";
                                status: "running" | "done" | "failed";
                                /** Format: date-time */
                                startedAt: string;
                                finishedAt: string | null;
                                files: number | null;
                                turns: number | null;
                                skills: number | null;
                                gates: number | null;
                                decisions: number | null;
                                error: string | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            accepted: true;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                            /** @enum {string} */
                            db: "up";
                        };
                    };
                };
                /** @description Default Response */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: false;
                            /** @enum {string} */
                            db: "down";
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
